WatchTime/Models/Producer.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WatchTime.Models
{
    public class Producer
    {
        [JsonProperty("Id")]
        public int Id { get; set; }
        [JsonProperty("Name")]
        public string Name { get; set; }
        [JsonProperty("YearOfEstablishment")]
        public int YearOfEstablishment { get; set; }
    }
}

WatchTime/Models/Series.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WatchTime.Models
{
    public class Series
    {
        [JsonProperty("Id")]
        public int Id { get; set; }
        [JsonProperty("Name")]
        public string Name { get; set; }
        [JsonProperty("SeasonsNumber")]
        public int SeasonsNumber { get; set; }
        [JsonProperty("YearOfProduction")]
        public int YearOfProduction { get; set; }
        [JsonProperty("Time")]
        public TimeSpan Time { get; set; }
    }
}

WatchTime/Models/Tag.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WatchTime.Models
{
    public class Tag
    {
        [JsonProperty("Id")]
        public int Id { get; set; }
        [JsonProperty("Category")]
        public string Category { get; set; }
    }
}

WatchTime/Models/User.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WatchTime.Models
{
    public class User
    {
        [JsonProperty("Login")]
        public string Login { get; set; }
        [JsonProperty("Password")]
        public string Password { get; set; }
        [JsonProperty("Email")]
        public string Email { get; set; }
        [JsonProperty("Role")]
        public string Role { get; set; }
        [JsonProperty("ToWatchTime")]
        public long ToWatchTime { get; set; }
        [JsonProperty("WatchedTime")]
        public long WatchedTime { get; set; }
    }
}

WatchTime/ViewModels/SeriesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WatchTime.Models;

namespace WatchTime.ViewModels
{
    public class SeriesViewModel
    {
        public List<Series> Suggested { set; get; }
        public List<Series> Watched { set; get; }
        public List<Series> ToWatch { set; get; }
        public List<Series> Series { set; get; }
    }
}

WatchTime/Controllers/HomeController.cs
using CypherNet.Graph;
using Neo4jClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchTime.Core;
using WatchTime.Models;

namespace WatchTime.Controllers
{
    public class HomeController : Controller
    {
        private WatchTimeQueries WatchTimeQueries;

        public HomeController()
        {
            WatchTimeQueries = new WatchTimeQueries();
        }

        public ActionResult Index()
        {
            if (Session["email"] != null)
            {
                Response.Redirect("/Series");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(string email, string password)
        {
            var user = WatchTimeQueries.Login(email, password);
            if (user != null)
            {
                Session["email"] = user.Email;
                Session["login"] = user.Login;
            }
            return View();
        }

    }
}

WatchTime/Controllers/ProducerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchTime.Core;
using WatchTime.Models;

namespace WatchTime.Controllers
{
    public class ProducerController : Controller
    {

        private WatchTimeQueries WatchTimeQueries;

        public ProducerController()
        {
            WatchTimeQueries = new WatchTimeQueries();
        }

        public ActionResult Index()
        {
            if (Session["email"] == null)
            {
                Response.Redirect("~/");
                return View();
            }
            else
            {
                var producers = WatchTimeQueries.GetProducers();
                return View(producers);
            }
        }

        public ActionResult Details(int id)
        {
            var series = WatchTimeQueries.GetToWatchSeriesByProducer(id, 3);
            return View(series);
        }

    }
}

WatchTime/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchTime.Core;
using WatchTime.Models;

namespace WatchTime.Controllers
{
    public class RegisterController : Controller
    {

        private WatchTimeQueries WatchTimeQueries;

        public RegisterController()
        {
            WatchTimeQueries = new WatchTimeQueries();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string login, string email, string password)
        {
            if(!WatchTimeQueries.IsUserExists(login, email))
            {
                WatchTimeQueries.Register(login, email, password);
            }
            return View();
        }

    }
}

WatchTime/Controllers/SeriesController.cs
using CypherNet.Graph;
using Neo4jClient;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchTime.Core;
using WatchTime.Models;
using WatchTime.ViewModels;

namespace WatchTime.Controllers
{
    public class SeriesController : Controller
    {
        private WatchTimeQueries WatchTimeQueries;

        public SeriesController()
        {
            WatchTimeQueries = new WatchTimeQueries();
        }

        public ActionResult Index()
        {
            if (Session["login"] == null)
            {
                Response.Redirect("~/");
                return View();
            }
            else
            { 
                var seriesViewModel = new SeriesViewModel
                {
                    Series = WatchTimeQueries.GetSeries(),
                    ToWatch = WatchTimeQueries.GetToWatchSeries(Session["login"].ToString()),
                    Watched = WatchTimeQueries.GetWatchedSeries(Session["login"].ToString()),
                    Suggested = WatchTimeQueries.GetSuggestedSeries(Session["login"].ToString(), 5)
                };
                return View(seriesViewModel);
            }
        }

        [HttpGet]
        public void UpdateWatchedSeries(int seriesId, bool createRelation)
        {
            WatchTimeQueries.AddWatchedSeries(seriesId, Session["login"].ToString(), createRelation);
            Response.Redirect("/Series");
        }

        [HttpGet]
        public void UpdateToWatchSeries(int seriesId, bool createRelation)
        {
            WatchTimeQueries.AddToWatchSeries(seriesId, Session["login"].ToString(), createRelation);
            Response.Redirect("/Series");
        }

    }
}

WatchTime/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchTime.Core;

namespace WatchTime.Controllers
{
    public class TagController : Controller
    {

        public WatchTimeQueries WatchTimeQueries;

        public TagController()
        {
            WatchTimeQueries = new WatchTimeQueries();
        }

        // GET: Tag
        public ActionResult Index()
        {
            if (Session["email"] == null)
            {
                Response.Redirect("~/");
                return View();
            }
            else
            {
                var tags = WatchTimeQueries.GetTags();
                return View(tags);
            }
        }

        public ActionResult Details(int id)
        {
            var series = WatchTimeQueries.GetMostPopularSeriesByTag(Session["login"].ToString(), id, 5);
            return View(series);
        }
    }
}

WatchTime/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="login-form">
    <form action="/Home/Index" method="post">
        <h4>Login</h4>
        <fieldset>
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="password" required>
            </div>
        </fieldset>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
    <p class="register-link">or @Html.ActionLink("Create an account", "Index", "Register", null, null)</p>
</div>

WatchTime/Views/Producer/Details.cshtml
@model IEnumerable<WatchTime.Models.Series>
@{
    ViewBag.SeriesList = "Popular to watch series";
}
<h2>@ViewBag.SeriesList</h2>
<br />
<div class="series-list">
    <table class="table table-hover">
        <thead>
            <tr class="table-active">
                <th scope="col">Series name</th>
                <th scope="col">Seasons number</th>
                <th scope="col">Year of production</th>
                <th scope="col">Time</th>
            </tr>
        </thead>
        <tbody>
            @{
                if (Model != null)
                {
                    foreach (var series in Model)
                    {
                        <tr class="table-light">
                            <th scope="row">@series.Name</th>
                            <td>@series.SeasonsNumber</td>
                            <td>@series.YearOfProduction</td>
                            <td>@series.Time</td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
</div>

WatchTime/Views/Producer/Index.cshtml
@model IEnumerable<WatchTime.Models.Producer>
@{
    ViewBag.Title = "Producers list";
}

<h2>@ViewBag.Title</h2>
<br />
<div class="producers-list">
    <table class="table table-hover">
        <thead>
            <tr class="table-active">
                <th scope="col">Name</th>
                <th scope="col">YearOfEstablishment</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var producer in Model)
                {
                    <tr class="table-light">
                        <th scope="row">@Html.ActionLink(producer.Name, "Details", "Producer", new { id = producer.Id }, new { @class = "nav-link" })</th>
                        <td>@producer.YearOfEstablishment</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

WatchTime/Views/Register/Index.cshtml
@{
    ViewBag.Title = "Register";
}

<div class="register-form">
    <form action="/Register/Index" method="post">
        <h4>Register</h4>
        <fieldset>
            <div class="form-group">
                <label for="login">Login</label>
                <input type="text" name="login" class="form-control" id="login" required>
            </div>
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="password" required>
            </div>
        </fieldset>
        <button type="submit" class="btn btn-primary">Confirm</button>
    </form>
</div>

WatchTime/Views/Series/Index.cshtml
@model WatchTime.ViewModels.SeriesViewModel
@{
    ViewBag.SuggestedSeries = "Recommended series";
    ViewBag.SeriesList = "Series list";
    ViewBag.ToWatch = "To watch list";
    ViewBag.Watched = "Watched list";
}

<h2>@ViewBag.SuggestedSeries</h2>
<br />
<div class="suggested-series-list">
    <table class="table table-hover">
        <thead>
            <tr class="table-active">
                <th scope="col">Series name</th>
                <th scope="col">Seasons number</th>
                <th scope="col">Year of production</th>
                <th scope="col">Time</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var series in Model.Suggested)
                {
                    <tr class="table-light">
                        <th scope="row">@series.Name</th>
                        <td>@series.SeasonsNumber</td>
                        <td>@series.YearOfProduction</td>
                        <td>@series.Time</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<h2>@ViewBag.ToWatch</h2>
<br />
<div class="to-watch-list">
    <table class="table table-hover">
        <thead>
            <tr class="table-active">
                <th scope="col">Series name</th>
                <th scope="col">Seasons number</th>
                <th scope="col">Year of production</th>
                <th scope="col">Time</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var series in Model.ToWatch)
                {
                    <tr class="table-light">
                        <th scope="row">@series.Name</th>
                        <td>@series.SeasonsNumber</td>
                        <td>@series.YearOfProduction</td>
                        <td>@series.Time</td>
                        <td>
                            <form action="@Url.Action("UpdateToWatchSeries", "Series")" method="get">
                                <input type="hidden" name="seriesId" value="@series.Id" />
                                <button type="submit" name="createRelation" value="false"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<h2>@ViewBag.Watched</h2>
<br />
<div class="watched-list">
    <table class="table table-hover">
        <thead>
            <tr class="table-active">
                <th scope="col">Series name</th>
                <th scope="col">Seasons number</th>
                <th scope="col">Year of production</th>
                <th scope="col">Time</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var series in Model.Watched)
                {
                    <tr class="table-light">
                        <th scope="row">@series.Name</th>
                        <td>@series.SeasonsNumber</td>
                        <td>@series.YearOfProduction</td>
                        <td>@series.Time</td>
                        <td>
                            <form action="@Url.Action("UpdateWatchedSeries", "Series")" method="get">
                                <input type="hidden" name="seriesId" value="@series.Id" />
                                <button type="submit" name="createRelation" value="false"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<h2>@ViewBag.SeriesList</h2>
<br />
<div class="series-list">
    <table class="table table-hover">
        <thead>
            <tr class="table-active">
                <th scope="col">Series name</th>
                <th scope="col">Seasons number</th>
                <th scope="col">Year of production</th>
                <th scope="col">Time</th>
                <th scope="col">To watch</th>
                <th scope="col">Watched</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var series in Model.Series)
                {
                    <tr class="table-light">
                        <th scope="row">@series.Name</th>
                        <td>@series.SeasonsNumber</td>
                        <td>@series.YearOfProduction</td>
                        <td>@series.Time</td>
                        <td>
                            <form action="@Url.Action("UpdateToWatchSeries", "Series")" method="get">
                                <input type="hidden" name="seriesId" value="@series.Id" />
                                <button type="submit" name="createRelation" value="true"><i class="fa fa-star"></i></button>
                            </form>
                        </td>
                        <td>
                            <form action="@Url.Action("UpdateWatchedSeries", "Series")" method="get">
                                <input type="hidden" name="seriesId" value="@series.Id" />
                                <button type="submit" name="createRelation" value="true"><i class="fa fa-star"></i></button>
                            </form>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

WatchTime/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WatchTime</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/HomeStyle.css" rel="stylesheet" />
    <link href="~/Content/RegisterStyle.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()

    </div>
    <footer>
        <hr />
        <p>&copy; @DateTime.Now.Year -WatchTime</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WatchTime/Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    @{ if (Session["email"] != null)
        {
            @Html.ActionLink("WatchTime", "Index", "Series", new { area = "" }, new { @class = "navbar-brand" })
        }
        else
        {
            @Html.ActionLink("WatchTime", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        }
    }
    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                @{ if (Session["email"] != null)
                    {
                        @Html.ActionLink("Home", "Index", "Series", null, new { @class = "nav-link" })
                    }
                    else
                    {
                        @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                    }
                }
            </li>
            @{
                if (Session["email"] != null)
                {
                    <li class="nav-item">
                        @Html.ActionLink("Series", "Index", "Series", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Producers", "Index", "Producer", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Tags", "Index", "Tag", null, new { @class = "nav-link" })
                    </li>
                }
            }
        </ul>
    </div>
</nav>

WatchTime/Views/Tag/Details.cshtml
@model IEnumerable<WatchTime.Models.Series>
@{
    ViewBag.SeriesList = "Most popular series by tag";
}
<h2>@ViewBag.SeriesList</h2>
<br />
<div class="series-list">
    <table class="table table-hover">
        <thead>
            <tr class="table-active">
                <th scope="col">Series name</th>
                <th scope="col">Seasons number</th>
                <th scope="col">Year of production</th>
                <th scope="col">Time</th>
            </tr>
        </thead>
        <tbody>
            @{
                if (Model != null)
                {
                    foreach (var series in Model)
                    {
                        <tr class="table-light">
                            <th scope="row">@series.Name</th>
                            <td>@series.SeasonsNumber</td>
                            <td>@series.YearOfProduction</td>
                            <td>@series.Time</td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
</div>

WatchTime/Views/Tag/Index.cshtml
@model IEnumerable<WatchTime.Models.Tag>
@{
    ViewBag.Title = "Tags";
}

<h2>@ViewBag.Title</h2>
<br />
<div class="tags-list">
    <table class="table table-hover">
        <thead>
            <tr class="table-active">
                <th scope="col">Name</th>
            </tr>
        </thead>
        <tbody>
            @{
                if (Model != null)
                {
                    foreach (var tag in Model)
                    {
                        <tr class="table-light">
                            <th scope="row">@Html.ActionLink(tag.Category, "Details", "Tag", new { id = tag.Id }, new { @class = "nav-link" })</th>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
</div>